### GET ALL DATA
GET http://localhost:8081/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJsYXlob21lMTIiLCJpYXQiOjE2NTMyODEyMTEsImV4cCI6MTY1MzI4MTI0MX0.j-JOm5lDR-ga6XvHA_ImrCWiYtBjODKMo_atFgROJt8

### GET ONE DATA
GET http://localhost:8081/api/users/1

### CREATE DATA
POST http://localhost:8081/api/users
Content-Type: application/json

{
    "username":"layhome12",
    "password":"password",
    "user_nama":"Layhome Sync"
}

### UPDATE DATA
PUT http://localhost:8081/api/users/1
Content-Type: application/json

{
    "password":"password"
}

### DELETE DATA

DELETE http://localhost:8081/api/users/1

### AUTHENTICATE
POST http://localhost:8081/api/auth
Content-Type: application/json

{
    "username":"layhome12",
    "password":"password"
}

### REFRESH TOKEN
GET http://localhost:8081/api/auth/refresh

### LOGOUT
GET http://localhost:8081/api/logout


