### GET ALL DATA
GET http://localhost:8081/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJsYXlob21lMTIiLCJpYXQiOjE2NTMyODc4NjEsImV4cCI6MTY1MzI4ODc2MX0.HFqDM81YkZymvKbpgAX2JvUAXqJ26cP4knCXn9pp--A

### GET ONE DATA
GET http://localhost:8081/api/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJsYXlob21lMTIiLCJpYXQiOjE2NTMyODc5NDcsImV4cCI6MTY1MzI4ODg0N30.8lkaULyrZON2s6XZa023dyvvtc8Kski9vm_IP7v0Ymc

### CREATE DATA
POST http://localhost:8081/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJsYXlob21lMTIiLCJpYXQiOjE2NTMyODU3NzgsImV4cCI6MTY1MzI4NjY3OH0.nAjPgzcdS6YhGuKyUb9yH6ZOlKHuPp3npypOg5-At5c
Content-Type: application/json

{
    "username":"astro12",
    "password":"password",
    "user_nama":"Astro Sync"
}

### UPDATE DATA
PUT http://localhost:8081/api/users/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJsYXlob21lMTIiLCJpYXQiOjE2NTMyODU3NzgsImV4cCI6MTY1MzI4NjY3OH0.nAjPgzcdS6YhGuKyUb9yH6ZOlKHuPp3npypOg5-At5c
Content-Type: application/json

{
    "username":"username",
    "password":"password",
    "user_nama":"User 1"
}

### DELETE DATA

DELETE http://localhost:8081/api/users/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJsYXlob21lMTIiLCJpYXQiOjE2NTMyODU3NzgsImV4cCI6MTY1MzI4NjY3OH0.nAjPgzcdS6YhGuKyUb9yH6ZOlKHuPp3npypOg5-At5c

### AUTHENTICATE
POST http://localhost:8081/api/auth
Content-Type: application/json

{
    "username":"layhome12",
    "password":"password"
}

### REFRESH TOKEN
GET http://localhost:8081/api/auth/refresh

### LOGOUT
GET http://localhost:8081/api/logout


